### PR TITLE
Update build infrastructure

### PR DESCRIPTION
**Pull request by wmdietl**
Attempt to set up a GitHub workflow that ensures the CF dependencies are up-to-date and built.

### CODE REVIEW

**Comment by wmdietl** [comment]
@cpovirk The GitHub workflow now successfully builds: https://github.com/wmdietl/nullness-checker-for-checker-framework/runs/1295422104

**Comment by cpovirk** [comment]
Thanks! I have been not looking forward to having to figure this out myself.

I have mild reservations about automatically updating an existing Git client for our CF fork. (In contrast, downloading it when it's not present is definitely a plus.) Largely, that just isn't the kind of thing I expect a build to do. (But I know that a multi-repo effort puts us in an awkward position no matter what.) I also wonder if it's eventually going to surprise me when I'm trying to work in a branch in the CF fork or something?? But I haven't thought this through.

If you'd like to keep it, I can still get behind that -- as long as you have some advice on how to turn it off (presumably without editing build.gradle, since I would inevitably accidentally commit the result :)). I'm already in the habit of running my own wrapper test script around ./gradlew, so I'm happy to pass some kind of flag to that command.

**Comment by wmdietl** [comment]
I'm fine with not automatically pulling from the CF clone if it already exists.
I didn't figure out how to add a gradle property for this, so commented out the code.
Note that the CF `cloneAndBuildDependencies` target will still update all its dependencies automatically. But as long as we don't have forks of anything other than the CF that won't bother you.

**Comment by cpovirk** [comment]
Oops, and now I try this, and I see that `ensureCheckerFrameworkBuilt` runs even for commands like `./gradlew help`. I tried to exclude it with `-x ensureCheckerFrameworkBuilt`, but that doesn't appear to help. I suspect this is my ignorance of Gradle showing. Any tips?

(Maybe I should just not worry about it. However, while I already have CF built in that directory, I might not have it "built enough," as `cloneAndBuildDependencies` is taking some time. I think I may have run only `assemble` for CF?)

**Comment by cpovirk** [comment]
Perhaps https://stackoverflow.com/a/30797819/28465?

**Comment by cpovirk** [comment]
Yep, that did it: https://github.com/jspecify/nullness-checker-for-checker-framework/commit/597bc312b94a3889836e6b79ca15eca0d268d82f.

(I don't know Gradle, so there may be better ways.)

**Comment by wmdietl** [comment]
Thanks for figuring this out! I also don't know Gradle, so I can't suggest alternatives.

**Pull request merged**
